In [2]:
#Basic statistic mean, median, mode)

import pandas as pd

In [3]:
df = pd.read_excel('cleaned_dataset.xlsx')

In [4]:
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,04-01-23,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,23-08-24,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,27-02-24,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,15-10-23,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,08-05-25,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,20-06-24,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,04-03-24,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NONE,Facebook,1325.06
1197,ORD201197,13-07-23,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,22-08-24,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,11-06-23,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [5]:
#Overall stat for numeric column

df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [14]:
#specific stat

df['TotalPrice'].mean()

np.float64(1053.9683)

In [13]:
df['TotalPrice'].median()   #middle value

823.615

In [16]:
df['TotalPrice'].mode()  #most occurng value

0     211.14
1     367.34
2     410.52
3     635.90
4    2517.36
Name: TotalPrice, dtype: float64

In [21]:
df['TotalPrice'].value_counts() #number of orders

TotalPrice
211.14     2
635.90     2
367.34     2
410.52     2
2517.36    2
          ..
538.68     1
640.88     1
2119.65    1
269.65     1
2242.32    1
Name: count, Length: 1195, dtype: int64

In [23]:
df['Product'].value_counts()   #order per product

Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64

In [25]:
df['OrderStatus'].value_counts()     #how many ship delivered

OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

In [26]:
df['PaymentMethod'].value_counts()      #popular paymentcard

PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64

In [ ]:
# Identifying trend and outliers

In [ ]:
# Trend sales over time

In [36]:
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.to_period('M')
monthly_sales = df.groupby('Month')['TotalPrice'].sum()
print(monthly_sales)

Month
2023-01    48995.02
2023-02    49567.96
2023-03    47654.19
2023-04    36953.76
2023-05    55973.84
2023-06    40017.66
2023-07    39507.72
2023-08    55098.61
2023-09    32019.32
2023-10    44055.77
2023-11    62106.74
2023-12    40692.65
2024-01    31715.80
2024-02    36062.29
2024-03    32658.63
2024-04    40397.70
2024-05    28822.34
2024-06    57610.11
2024-07    55816.65
2024-08    37521.51
2024-09    39950.59
2024-10    42315.47
2024-11    41194.25
2024-12    36170.53
2025-01    27988.42
2025-02    31081.76
2025-03    27933.09
2025-04    29473.27
2025-05    30319.85
2025-06    41093.50
2025-07     9305.68
2025-08    11535.59
2025-09     5204.53
2025-10     8222.74
2025-11     4067.94
2025-12     5656.48
Freq: M, Name: TotalPrice, dtype: float64

In [45]:
# outliers - orders with unsual high/low price 

Q1 = df['TotalPrice'].quantile(0.25)
Q3 = df['TotalPrice'].quantile(0.75)
IQR = Q3  -Q1

outliers = df[(df['TotalPrice'] < Q1 -1.5*IQR) |
              (df['TotalPrice'] > Q3  + 1.5*IQR)]
print(f"outliers found {len(outliers)}")

outliers found 8

In [ ]:
#key summary

In [47]:
print("Total Revenue:", df['TotalPrice'].round(2))

Total Revenue: 0       2853.10
1        302.70
2       2753.40
3        273.19
4       2504.04
         ...
1195     107.04
1196    1325.06
1197     873.68
1198    1050.08
1199    2242.32
Name: TotalPrice, Length: 1200, dtype: float64

In [49]:
print("Average Oder Value:", df['TotalPrice'].mean().round(2))

Average Oder Value: 1053.97

In [52]:
print("best selling product:", df['Product'].value_counts().idxmax())

best selling product: Printer

In [53]:
print("most used payment method:", df['PaymentMethod'].value_counts().idxmax())

most used payment method: Online

In [58]:
print("Most Ordered Status:", df['OrderStatus'].value_counts().idxmax())

Most Ordered Status: Cancelled